### ISSUE TITLE
Support Xcode 7 building of Swift Projects

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/Makr#8]
The new procedure looks like this:
https://github.com/willowtreeapps/burst-ios/blob/develop/scripts/build.sh#L39

What's going on here:
- A [plist](https://github.com/willowtreeapps/burst-ios/blob/develop/signing/appstore.plist) is passed in and used in the export process to determine HOW to export
  - This is created by the user and should just be a file that is located somewhere in the root of the repo.
  -  You can see possible keys in xcodebuild -help
- An archive is passed in

Pretty straight forward, but what this ultimately does is provide the same functionality you would get if you exported the archive from organizer. You get all the options that are present in that flow.

This will not work on < Xcode 7

**Comment by andrewroycarter** [comment]
Done!
